version: '3.6'

services:
  database:
    container_name: go_notes_pg_container
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "${DB_NAME:-go_notes}"
      POSTGRES_USER: "${DB_USER:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASS:-postgres}"
    ports:
      - "${DB_PORT:-5434}:5432"
    restart: always
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    container_name: go_notes_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD:-admin}'
    ports:
      - "${PGADMIN_PORT:-5052}:80"
    depends_on:
      - database
    links:
      - database
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres

  redis:
    container_name: go_notes_redis_container
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6381}:6379"
    restart: always
    networks:
      - postgres

  # app:
  #   container_name: go_notes_app_container
  #   build: .
  #   # ports:
  #   #   - "${HOST_PORT:-8088}:8088"
  #   restart: always
  #   depends_on:
  #     - database
  #     - redis
  #   networks:
  #     - postgres

volumes:
    postgres:
    pgadmin:

networks:
  postgres:
    driver: bridge