CREATE TABLE IF NOT EXISTS notes(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    author_id INTEGER NOT NULL,
    body TEXT NOT NULL,
    is_public BOOLEAN NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);